USE SECONDARY ROLES ALL;

--How many single-family homes with central AC and heat with natural gas in Minnesota grouped by wall type?

WITH CTE AS (
SELECT rd.DOEID, rd.state_name, rd.HDD30YR_PUB, rd.TYPEHUQ, rd.WALLTYPE, rd.ACEQUIPM_PUB, rd.FUELHEAT
FROM RECS_DB.RECS_DATA_SCHEMA.RECS_DATA rd
INNER JOIN RECS_DB.CODES_SCHEMA.TYPE_TYPEHUQ thuq
ON rd.TYPEHUQ = thuq.CODE
INNER JOIN RECS_DB.CODES_SCHEMA.TYPE_ACEQUIPM_PUB tace
ON rd.ACEQUIPM_PUB = tace.CODE
INNER JOIN RECS_DB.CODES_SCHEMA.TYPE_FUELHEAT tfh
ON rd.FUELHEAT = tfh.CODE
WHERE LOWER(rd.state_name)='minnesota' 
AND rd.HDD30YR_PUB>=7000
AND LOWER(thuq.CODE_DESC) LIKE '%single-family%' 
AND LOWER(tace.CODE_DESC) LIKE '%central air condition%'
AND LOWER(tfh.CODE_DESC) LIKE '%natural gas%'
)

SELECT CTE.WALLTYPE, WT.CODE_DESC AS WALLTYPE_DESCRIPTION, COUNT(*) AS NUMBER_OF_HOMES,  
FROM CTE JOIN RECS_DB.CODES_SCHEMA.TYPE_WALLTYPE WT ON CTE.WALLTYPE = WT.CODE
GROUP BY CTE.WALLTYPE, WT.CODE_DESC
ORDER BY 1 ASC;